using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace DungeonMaster
{
    /// <summary>Autogenerated Class from ASPNET/BLAZOR</summary>
    public class Program
    {

        /// <summary>Defines the entry point of the application.
        /// Autogenerated from ASPNET</summary>
        /// <param name="args">The arguments.</param>
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();

        }

        /// <summary>Creates the host builder.
        /// Autogenerated from ASPNET.</summary>
        /// <param name="args">The arguments.</param>
        /// <returns>IHostBuilder.</returns>
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
